### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by Svenito** [wieden-kennedy/Cinder-KCB2#15]
Is this supported? I am getting errors both when trying to use the block (Unable to copy from .... blocks/Cinder-KCB2/lib/$(PlatformTarget)/$(Configuration) etc) and when building, the faceApp for example:

Error	1	error C2039: 'Channel8uRef' : is not a member of 'cinder'	
\cinder-kcb2\src\kinect2.h	64	1	FaceApp
Error	14	error C2039: 'vec2' : is not a member of 'cinder'	\cinder-kcb2\src\kinect2.h	72	1	FaceApp

I copied the repo into the blocks folder, then launched the tinderbox exe from the master branch. I'm not very familiar with Windows tools, as I usually work in Linux, so could be an error on my side.

**Comment by vertgo** [comment]
Hey @Svenito,
This seems to be a known issue.
https://github.com/wieden-kennedy/Cinder-KCB2/issues/7

Does that help?

**Comment by Svenito** [comment]
I'll give this a go, thanks. Pretty sure it'll work for the Tinder box case. Not sure about the `vec2` vs `Vec2` issue

**Comment by vertgo** [comment]
Actually @Svenito,
I rewrote that xml file, now having another problem. As it is, this doesn't seem to work. I had to switch to the dev branch of tinderbox.

**Comment by Svenito** [comment]
Fixed this by editing the XML file as per issue #7 - use x86 not 64 bit. Also have to use glNext branch of Cinder

**Comment by Svenito** [comment]
Although unable to run it. Error 0xc000007b - apparently related to picking up some 64bit libs when it shouldn't be. The samples run, and I'm not seeing any major differences between the two projects.

**Comment by Svenito** [comment]
It was copying over the wring KCBv2.dll. Fixed it in project settings post-build scripts
